server:
  port: 8803
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    network-configuration-server:
      path: /network-configuration/**
      url: http://localhost:8811/network-configuration
    branch-management:
      path: /branch-management/**
      url: http://localhost:8811/branch-management
    oauth:
      path: /authentication/**
      url: http://localhost:8804/spring-security-oauth-server
security:
  oauth2:
    resource:
      jwt:
        key-value: 123